[general]
static=yes
writeprotect=no

[default]
exten => s,1,Answer()
 same => n,Wait(1)
 same => n,Background(enter-ext-of-person)
 same => n,WaitExten(10)
 same => n,Hangup()

exten => 1,1,Goto(201,1)
exten => 2,1,Goto(202,1)
exten => 3,1,Goto(301,1)
exten => 4,1,Goto(302,1)

exten => 201,1,Dial(PJSIP/201@ht812,30)
 same => n,Hangup()
exten => 202,1,Dial(PJSIP/202@ht812,30)
 same => n,Hangup()
exten => 301,1,Dial(PJSIP/301@ht812,30)
 same => n,Hangup()
exten => 302,1,Dial(PJSIP/302@ht812,30)
 same => n,Hangup()
