[global]
user_agent=Asterisk Building

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[ht812]
; Grandstream HT812 SIP trunk
 type=endpoint
 transport=transport-udp
 context=default
 disallow=all
 allow=ulaw
 aors=ht812

[ht812]
 type=aor
 contact=sip:ht812:5060

